<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Source\Automation\WebsiteRegressionProduction\WebsiteRegressionProduction\bin\Debug\WebsiteRegressionProduction.nunit" total="2" errors="1" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2013-09-09" time="13:04:14">
  <environment nunit-version="2.6.2.12296" clr-version="4.0.30319.18052" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.2\bin" machine-name="DEVERETT-PC" user="deverett" user-domain="APEX" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Project" name="C:\Source\Automation\WebsiteRegressionProduction\WebsiteRegressionProduction\bin\Debug\WebsiteRegressionProduction.nunit" executed="False" result="Cancelled">
    <results>
      <test-suite type="Assembly" name="C:\Source\Automation\WebsiteRegressionProduction\WebsiteRegressionProduction\bin\Debug\WebsiteRegressionProduction.dll" executed="False" result="Cancelled">
        <results>
          <test-suite type="Namespace" name="WebsiteRegressionProduction" executed="False" result="Cancelled">
            <results>
              <test-suite type="TestFixture" name="ConfigurationFiles" executed="True" result="Success" success="True" time="0.480" asserts="0">
                <results>
                  <test-case name="WebsiteRegressionProduction.ConfigurationFiles.TheConfigurationFilesTest" executed="True" result="Success" success="True" time="0.430" asserts="0" />
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="Dental5010" executed="False" result="Cancelled">
                <results>
                  <test-case name="WebsiteRegressionProduction.Dental5010.TheUploadAndProcessDental5010Test" executed="False" result="Cancelled">
                    <failure>
                      <message><![CDATA[Test cancelled by user]]></message>
                      <stack-trace><![CDATA[at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at NUnit.Core.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
at NUnit.Core.TestMethod.RunTestMethod(TestResult testResult)
at NUnit.Core.TestMethod.RunTestCase(TestResult testResult)
]]></stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>